http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  api:
    host:'localhost'
    paths:'/auth'
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  auth:
    url:'localhost:5001'
    # paths:'/auth'
  # supply:
  #   url:'localhost:5003'
  #   # paths:'/supply'
  # payment:
  #   url:'localhost:5002'
  #   # paths:'/payment'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines