module.exports.authService = require('./auth.service');
// module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.billService = require('./bill.service');
module.exports.feedbackService = require('./feedback.service');
module.exports.hotelService = require('./hotel.service');
module.exports.restaurantService = require('./restaurant.service');
module.exports.selfVehicleService = require('./selfVehicle.service');
module.exports.userService = require('./user.service');
